/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class dataadmin extends javax.swing.JFrame {

    /**
     * Creates new form dataadmin
     */
    public dataadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        tblSimpan = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        tblKeluar = new javax.swing.JButton();
        tblUbah = new javax.swing.JButton();
        minimaze = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("ADMIN YANG BERTUGAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel1.setText("NIP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 20));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 204, -1, 30));

        jLabel5.setText("No Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, -1));

        jk.add(jRadioButton1);
        jRadioButton1.setText("Laki-laki");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jk.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jenis Kelamin", "No. Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableadmin);
        if (tableadmin.getColumnModel().getColumnCount() > 0) {
            tableadmin.getColumnModel().getColumn(0).setResizable(false);
            tableadmin.getColumnModel().getColumn(1).setResizable(false);
            tableadmin.getColumnModel().getColumn(2).setResizable(false);
            tableadmin.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 530, 100));

        tblSimpan.setBackground(new java.awt.Color(0, 51, 255));
        tblSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tblSimpan.setText("Simpan");
        tblSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 30));

        tblHapus.setBackground(new java.awt.Color(0, 51, 255));
        tblHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblHapus.setForeground(new java.awt.Color(255, 255, 255));
        tblHapus.setText(" HAPUS");
        tblHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, 30));

        tblKeluar.setBackground(new java.awt.Color(0, 51, 255));
        tblKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        tblKeluar.setText("   HOME");
        tblKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 110, 30));

        tblUbah.setBackground(new java.awt.Color(0, 51, 255));
        tblUbah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblUbah.setForeground(new java.awt.Color(255, 255, 255));
        tblUbah.setText("Ubah");
        tblUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });
        getContentPane().add(tblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 30));

        minimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimazeMouseClicked(evt);
            }
        });
        getContentPane().add(minimaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 3, 30, 20));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 3, 30, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/bg.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(680, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
        
    }//GEN-LAST:event_tblSimpanActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        int confirm2 = JOptionPane.showConfirmDialog(this,
            "Anda Yakin Untuk Menghapus Data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm2 == JOptionPane.YES_OPTION) {

            
        }
    }//GEN-LAST:event_tblHapusActionPerformed

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        new home().setVisible(true); dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
        
    }//GEN-LAST:event_tblUbahActionPerformed

    private void minimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimazeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimazeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Untuk Menutup Program?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) { System.exit(0); }
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JLabel minimaze;
    private javax.swing.JTable tableadmin;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblSimpan;
    private javax.swing.JButton tblUbah;
    // End of variables declaration//GEN-END:variables
}
