/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Acer
 */
public final class dataadmin extends javax.swing.JFrame {

    /**
     * Creates new form dataadmin
     */
    private final DefaultTableModel model;
    public dataadmin() {
        initComponents();
        model = new DefaultTableModel ( );
             tableadmin.setShowGrid(true);
             tableadmin.setModel(model);
             model.addColumn("NIP");
             model.addColumn("Nama");
             model.addColumn("Jenis Kelamin");
             model.addColumn("No Telepon");
        data();
        satuaja();
    }
    
    public void satuaja(){
        try {
           Statement stat = (Statement) Db_Koneksi2.getKoneksi( ).createStatement( );
           String sql        = "Select * from dataadmin;";
           ResultSet res   = stat.executeQuery(sql);
           while (res.next()){
               String trigger = res.getString("NIP");
                if (trigger != ""){
                    tblSimpan.setEnabled(false);
               } else {
                   tblSimpan.setEnabled(true);
               }
           }
           
        } catch (SQLException e) {}
    }
    
    public void data(){
        model.getDataVector( ).removeAllElements( );
        model.fireTableDataChanged( );
        try {
           Statement stat = (Statement) Db_Koneksi2.getKoneksi( ).createStatement( );
           String sql        = "Select * from dataadmin;";
           ResultSet res   = stat.executeQuery(sql);
            while (res.next())  {    
                nip.setText(res.getString("NIP"));
                nama.setText(res.getString("Nama_ADMIN"));
                if ("Laki-Laki".equals(res.getString("JenisKelamin"))) {
                    laki.setSelected(true); }
                if  ("Perempuan".equals(res.getString("JenisKelamin"))) {
                    cewe.setSelected(true); }
                notel.setText(res.getString("No_Telp"));
            }
        } catch (SQLException e) { }
        try {
                        Statement stat = (Statement) Db_Koneksi2.getKoneksi( ).createStatement( );
                        String sql2        = "Select * from dataadmin;";
                        ResultSet ress   = stat.executeQuery(sql2);
                        while (ress.next())  { 
                            Object[ ] obj = new Object[4];
                            obj[0] = ress.getString("NIP");
                            obj[1] = ress.getString("Nama_ADMIN");
                            obj[2] = ress.getString("JenisKelamin");
                            obj[3] = ress.getString("No_Telp");
                            model.addRow(obj);
                            }
                        } catch (SQLException e) { }
        satuaja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nip = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        notel = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        cewe = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        tblSimpan = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        tblKeluar = new javax.swing.JButton();
        tblUbah = new javax.swing.JButton();
        minimaze = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("ADMIN YANG BERTUGAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel1.setText("NIP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        jLabel5.setText("No Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));
        getContentPane().add(notel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, -1));

        jk.add(laki);
        laki.setText("Laki-laki");
        getContentPane().add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jk.add(cewe);
        cewe.setText("Perempuan");
        getContentPane().add(cewe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jenis Kelamin", "No. Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableadminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableadmin);
        if (tableadmin.getColumnModel().getColumnCount() > 0) {
            tableadmin.getColumnModel().getColumn(0).setResizable(false);
            tableadmin.getColumnModel().getColumn(1).setResizable(false);
            tableadmin.getColumnModel().getColumn(2).setResizable(false);
            tableadmin.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 530, 100));

        tblSimpan.setBackground(new java.awt.Color(0, 51, 255));
        tblSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tblSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/iconTambah.png"))); // NOI18N
        tblSimpan.setText("Simpan");
        tblSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, 30));

        tblHapus.setBackground(new java.awt.Color(0, 51, 255));
        tblHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblHapus.setForeground(new java.awt.Color(255, 255, 255));
        tblHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/iconHapus.png"))); // NOI18N
        tblHapus.setText(" HAPUS");
        tblHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, 30));

        tblKeluar.setBackground(new java.awt.Color(0, 51, 255));
        tblKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        tblKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/home2.png"))); // NOI18N
        tblKeluar.setText("   HOME");
        tblKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 110, 30));

        tblUbah.setBackground(new java.awt.Color(0, 51, 255));
        tblUbah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblUbah.setForeground(new java.awt.Color(255, 255, 255));
        tblUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/iconUbah.png"))); // NOI18N
        tblUbah.setText("Ubah");
        tblUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });
        getContentPane().add(tblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 30));

        minimaze.setToolTipText("Minimaze");
        minimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimazeMouseClicked(evt);
            }
        });
        getContentPane().add(minimaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 3, 30, 20));

        close.setToolTipText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 3, 30, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Input Data Admin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 20));

        alert.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/bg.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(680, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
    if (nip.getText().trim().equals("") || nama.getText().trim().equals("")|| notel.getText().trim().equals("")) 
            { alert.setText("Harap Masukkan Data Dengan Benar");
        } else {
            alert.setText("");
        String nip2 = nip.getText();
        String nama2 = nama.getText();
        String Jenis = null;
            if (laki.isSelected()) {
                Jenis ="Laki-Laki";
            }
            else if (cewe.isSelected()) {
                Jenis ="Perempuan";
            }
        String notel2 = notel.getText();
        try {
                try (Statement statement = (Statement)Db_Koneksi2.getKoneksi().createStatement()) {
                    statement.executeUpdate("insert into dataadmin values ('"+nip2+"','"+nama2+"','"+Jenis+"','"+notel2+"');");
                }
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                data();
        }catch (SQLException t){
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
       }        
    }//GEN-LAST:event_tblSimpanActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        int confirm2 = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Untuk Menghapus Data?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
        if (confirm2 == JOptionPane.YES_OPTION) {
        try {
            Statement statement = (Statement) Db_Koneksi2.getKoneksi().createStatement();
            statement.executeUpdate("delete from dataadmin where NIP= ('"+nip.getText()+"');");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            data();
            tblSimpan.setEnabled(true); nip.setText(""); nama.setText(""); notel.setText("");
        }catch (SQLException t) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
        }
        }
    }//GEN-LAST:event_tblHapusActionPerformed

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        new home().setVisible(true); dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
          if (nip.getText().trim().equals("") || 
            nama.getText().trim().equals("") || notel.getText().trim().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null,
                        "Isi semua data dengan benar",
                        "Pesan Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
            String nip2 = nip.getText();
            String Nama = nama.getText();
            String Jenis_Kelamin = null;
            if (laki.isSelected()) { Jenis_Kelamin ="Laki-Laki"; }
            if (cewe.isSelected()) {  Jenis_Kelamin ="Perempuan"; }
            String notel2 = notel.getText();
        try {
            try (Statement statement = (Statement) Db_Koneksi2.getKoneksi().createStatement()) {
                statement.executeUpdate("update dataadmin set Nama_ADMIN='"+Nama+"', JenisKelamin='"+Jenis_Kelamin+"', No_telp='"+notel2+"' where NIP='"+nip2+"';");
                }
            JOptionPane.showMessageDialog(null, "Data berhasil rubah");
            data();
        } catch (SQLException t){ JOptionPane.showMessageDialog(null, "Data gagal disimpan"); }
        }
        
    }//GEN-LAST:event_tblUbahActionPerformed

    private void minimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimazeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimazeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this,
        "Anda Yakin Untuk Menutup Program?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) { System.exit(0); }
    }//GEN-LAST:event_closeMouseClicked

    private void tableadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableadminMouseClicked
       int row = tableadmin.getSelectedRow();
        if (row != -1) {
            nip.setText(tableadmin.getValueAt(row, 0).toString());
            nama.setText(tableadmin.getValueAt(row, 1).toString());
            if ("Laki-Laki".equals(tableadmin.getValueAt(row, 2).toString())) {
                laki.setSelected(true); }
            if ("Perempuan".equals(tableadmin.getValueAt(row, 2).toString())) {
                cewe.setSelected(true); }
            notel.setText(tableadmin.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_tableadminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton cewe;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel minimaze;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField notel;
    private javax.swing.JTable tableadmin;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblSimpan;
    private javax.swing.JButton tblUbah;
    // End of variables declaration//GEN-END:variables
}
