/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class depan extends javax.swing.JFrame {

    /**
     * Creates new form depan
     */
    public depan() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        loginadmin = new javax.swing.JButton();
        loginasadmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN - Aplikasi Pengolahan Data Peserta Didik Baru");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        user.setBackground(new java.awt.Color(153, 204, 255));
        user.setToolTipText("username");
        user.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(user);
        user.setBounds(520, 180, 230, 28);

        loginadmin.setBackground(new java.awt.Color(153, 204, 255));
        loginadmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginadmin.setText("LOGIN ADMIN");
        loginadmin.setToolTipText("login admin");
        loginadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginadminActionPerformed(evt);
            }
        });
        getContentPane().add(loginadmin);
        loginadmin.setBounds(460, 280, 120, 40);

        loginasadmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginasadmin.setText("LOGIN AS ADMIN :");
        getContentPane().add(loginasadmin);
        loginasadmin.setBounds(460, 140, 250, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PADA SMP PGRI 1 CIPUTAT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 210, 300, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("APLIKASI PENGOLAHAN DATA PESERTA DIDIK BARU");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 400, 40);

        pass.setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().add(pass);
        pass.setBounds(520, 229, 230, 28);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/bg1.png"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(0, 1, 794, 471);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginadminActionPerformed
        try {
                Statement stat2 = (Statement) Db_Koneksi2.getKoneksi( ).createStatement( );
                String sql        = "Select*from login;";
                ResultSet ress;
                ress = stat2.executeQuery(sql);
                if (ress.next()) {
                    if (user.getText().equals(ress.getString("username")) &&
                        pass.getText().equals(ress.getString("password"))) {
                        javax.swing.JOptionPane.showMessageDialog(null,
                        "Anda berhasil masuk",
                        "Konfirmasi",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        new home().setVisible(true);
                    }
                    else {
                                user.setText("");
                                pass.setText("");
                                javax.swing.JOptionPane.showMessageDialog(null,
                        "Username atau Password salah",
                        "Coba Lagi",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                user.requestFocus();
                     }
                }
                ress.close(); 
                } catch (SQLException e) { }
      
    }//GEN-LAST:event_loginadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new depan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginadmin;
    private javax.swing.JLabel loginasadmin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
