/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author Acer
 */
public class depan extends javax.swing.JFrame {

    /**
     * Creates new form depan
     */
    public depan() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        loginadmin = new javax.swing.JButton();
        loginguest = new javax.swing.JButton();
        Silahkan = new javax.swing.JLabel();
        Silahkan1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN - Aplikasi Pengolahan Data Peserta Didik Baru");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        user.setBackground(new java.awt.Color(153, 204, 255));
        user.setToolTipText("username");
        user.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(user);
        user.setBounds(520, 180, 230, 28);

        pass.setBackground(new java.awt.Color(153, 204, 255));
        pass.setToolTipText("password");
        pass.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        getContentPane().add(pass);
        pass.setBounds(520, 229, 230, 28);

        loginadmin.setBackground(new java.awt.Color(153, 204, 255));
        loginadmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginadmin.setText("LOGIN ADMIN");
        loginadmin.setToolTipText("login admin");
        loginadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginadminActionPerformed(evt);
            }
        });
        getContentPane().add(loginadmin);
        loginadmin.setBounds(460, 280, 120, 40);

        loginguest.setBackground(new java.awt.Color(255, 0, 51));
        loginguest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginguest.setText("LOGIN GUEST");
        loginguest.setToolTipText("login guest");
        loginguest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginguest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginguestActionPerformed(evt);
            }
        });
        getContentPane().add(loginguest);
        loginguest.setBounds(460, 380, 120, 40);

        Silahkan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Silahkan.setText("LOGIN AS GUEST :");
        getContentPane().add(Silahkan);
        Silahkan.setBounds(460, 350, 250, 20);

        Silahkan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Silahkan1.setText("LOGIN AS ADMIN :");
        getContentPane().add(Silahkan1);
        Silahkan1.setBounds(460, 140, 250, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PADA SMP PGRI 1 CIPUTAT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 210, 300, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("APLIKASI PENGOLAHAN DATA PESERTA DIDIK BARU");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 400, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/bg1.png"))); // NOI18N
        background.setText("jLabel2");
        getContentPane().add(background);
        background.setBounds(0, 1, 794, 471);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginguestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginguestActionPerformed
        
    }//GEN-LAST:event_loginguestActionPerformed

    private void loginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginadminActionPerformed
        new home().setVisible(true); dispose();
    }//GEN-LAST:event_loginadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(depan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new depan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Silahkan;
    private javax.swing.JLabel Silahkan1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginadmin;
    private javax.swing.JButton loginguest;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
