/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form isiForm
     */
    public pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblMinimaze = new javax.swing.JLabel();
        tblExit = new javax.swing.JLabel();
        tabel = new javax.swing.JScrollPane();
        tabelsiswa = new javax.swing.JTable();
        tblSimpan = new javax.swing.JButton();
        tblBatal = new javax.swing.JButton();
        tblUbah = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        tblKeluar = new javax.swing.JButton();
        garis = new javax.swing.JPanel();
        garis2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ortu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        noabsen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 515));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMinimaze.setToolTipText("Minimaze");
        tblMinimaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblMinimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMinimazeMouseClicked(evt);
            }
        });
        getContentPane().add(tblMinimaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 3, 28, 20));

        tblExit.setToolTipText("Close");
        tblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExitMouseClicked(evt);
            }
        });
        getContentPane().add(tblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 3, 28, 20));

        tabelsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "NIS / NISN", "Nama", "Total Pembayaran", "Telah Dibayar", "Sisah Pembayaran", "Status"
            }
        ));
        tabelsiswa.setGridColor(new java.awt.Color(0, 102, 255));
        tabelsiswa.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tabelsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelsiswaMouseClicked(evt);
            }
        });
        tabel.setViewportView(tabelsiswa);

        getContentPane().add(tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 450, 270));

        tblSimpan.setBackground(new java.awt.Color(0, 51, 255));
        tblSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tblSimpan.setText("SIMPAN");
        tblSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 35));

        tblBatal.setBackground(new java.awt.Color(0, 51, 255));
        tblBatal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblBatal.setForeground(new java.awt.Color(255, 255, 255));
        tblBatal.setText("BATAL");
        tblBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBatalActionPerformed(evt);
            }
        });
        getContentPane().add(tblBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, 35));

        tblUbah.setBackground(new java.awt.Color(0, 51, 255));
        tblUbah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblUbah.setForeground(new java.awt.Color(255, 255, 255));
        tblUbah.setText("UBAH");
        tblUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });
        getContentPane().add(tblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 110, 35));

        tblHapus.setBackground(new java.awt.Color(0, 51, 255));
        tblHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblHapus.setForeground(new java.awt.Color(255, 255, 255));
        tblHapus.setText("HAPUS");
        tblHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 110, 35));

        tblKeluar.setBackground(new java.awt.Color(0, 51, 255));
        tblKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        tblKeluar.setText("   HOME");
        tblKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(tblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 110, 35));

        garis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout garisLayout = new javax.swing.GroupLayout(garis);
        garis.setLayout(garisLayout);
        garisLayout.setHorizontalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        garisLayout.setVerticalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(garis, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 415, 750, 2));

        garis2.setBackground(new java.awt.Color(255, 0, 0));
        garis2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        garis2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout garis2Layout = new javax.swing.GroupLayout(garis2);
        garis2.setLayout(garis2Layout);
        garis2Layout.setHorizontalGroup(
            garis2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        garis2Layout.setVerticalGroup(
            garis2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(garis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 750, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NIS / NISN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));
        getContentPane().add(ortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Total Pembayaran");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Telah Dibayar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, -1));
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));
        getContentPane().add(noabsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 60, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("PEMBAYARAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Sisah Pembayaran");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/gambar/depan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMinimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMinimazeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_tblMinimazeMouseClicked

    private void tblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExitMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this,
            "Anda Yakin Untuk Menutup Program?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_tblExitMouseClicked

    private void tabelsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelsiswaMouseClicked
        
    }//GEN-LAST:event_tabelsiswaMouseClicked

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
        

    }//GEN-LAST:event_tblSimpanActionPerformed

    private void tblBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBatalActionPerformed
       
    }//GEN-LAST:event_tblBatalActionPerformed

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
       
    }//GEN-LAST:event_tblUbahActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
       
    }//GEN-LAST:event_tblHapusActionPerformed

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        new home().setVisible(true); dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JPanel garis;
    private javax.swing.JPanel garis2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nis;
    private javax.swing.JTextField noabsen;
    private javax.swing.JTextField ortu;
    private javax.swing.JScrollPane tabel;
    private javax.swing.JTable tabelsiswa;
    private javax.swing.JButton tblBatal;
    private javax.swing.JLabel tblExit;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JLabel tblMinimaze;
    private javax.swing.JButton tblSimpan;
    private javax.swing.JButton tblUbah;
    // End of variables declaration//GEN-END:variables
}
